FROM python:3.9.7

WORKDIR $HOME/delinquency_analysis

COPY . $HOME/delinquency_analysis
RUN pip install -r requirements-analysis.txt

ENTRYPOINT ["jupyter", "lab", "--allow-root", "--port", "8889", "--ip=0.0.0.0", "--no-browser"]
